service: resize-avatar

frameworkVersion: '3'

custom:
  bucket_suffix:
    dev: 'production-thumb'
    staging: 'staging'
    prod: 'production-thumb'
  dir_prefix:
    dev: 'staging/'
    staging: 'users/'
    prod: ''
  connection-string:
    dev: 'PREPROD_DATABASE_URL'
    staging: 'PREPROD_DATABASE_URL'
    prod: 'PRODUCTION_DATABASE_URL'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'staging'}
  region: eu-west-1
  logRetentionInDays: 30
  environment :
    watch_bucket: "entourage-avatars-${self:custom.bucket_suffix.${self:provider.stage}}"
    watch_dir: "${self:custom.dir_prefix.${self:provider.stage}}300x300/"
    target_bucket: "entourage-avatars-${self:custom.bucket_suffix.${self:provider.stage}}"
    target_size: 300
    small_target_size: 60
    target_dir: "${self:custom.dir_prefix.${self:provider.stage}}300x300/"
    small_target_dir: "${self:custom.dir_prefix.${self:provider.stage}}60x60/"
    source_dir: "${self:custom.dir_prefix.${self:provider.stage}}source/"
    request_string: ${self:functions.resize-avatar.name}
    slacktoken: ${ssm:/ENTOURAGE_AWS_LAMBDA_APP_SLACK_TOKEN}
    channelId: 'CRNGQU2K1'
    dbconnectionstring: ${ssm:/${self:custom.connection-string.${self:provider.stage}}}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

functions:
  resize-avatar:
    name: resize-avatar-${self:provider.stage}
    handler: handler.resizeAvatar
    events:
      - s3:
          bucket: ${self:provider.environment.watch_bucket}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: ${self:provider.environment.watch_dir}
